<?php
/**
 * @file hosting_git_pull.module
 *
 * Provides a Hosting Queue and a URL callback for remote services to ping, in
 * order to trigger a Pull Code task.
 *
 * Used to keep a dev server up to date with the commits of projects.
 *
 */

define('HOSTING_GIT_PULL_DISABLED', 0);
define('HOSTING_GIT_PULL_QUEUE', 1);
define('HOSTING_GIT_PULL_CALLBACK', 2);

define('HOSTING_GIT_PULL_STATUS_OK', 1);
define('HOSTING_GIT_PULL_STATUS_ACCESS_DENIED', 2);
define('HOSTING_GIT_PULL_STATUS_INVALID_CODE', 3);

// These are github's Webhook callback IPs.
// This list grows occaisonally, update it as needed.
define('HOSTING_GIT_PULL_DEFAULT_ALLOWED_IPS', "
204.232.175.64/27
192.30.252.0/22
");

// The base URL to use for the Post Commit callback.
define('HOSTING_GIT_PULL_CALLBACK_URL', 'git/pull');

/**
 * Implements hook_hosting_tasks().
 */
function hosting_git_hosting_tasks() {
  $tasks = array();

  $tasks['site']['git-pull'] = array(
    'title' => t('Git pull'),
    'description' => t('Runs a git pull on the current site.'),
    'dialog' => TRUE,
  );

  $tasks['site']['git_clone'] = array(
    'title' => t('Git clone'),
    'description' => t('Clone a git repository in a location of your choice.'),
    'dialog' => TRUE,
  );

  $tasks['site']['git_checkout'] = array(
    'title' => t('Git checkout'),
    'description' => t('Perform a git checkout'),
    'dialog' => TRUE,
  );

  $tasks['platform']['git-pull'] = array(
    'title' => t('Git pull'),
    'description' => t('Runs a git pull on the current platform.'),
    'access callback' => 'hosting_git_access_platform_pull',
    'dialog' => TRUE,
  );

  return $tasks;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function hosting_git_access_platform_pull($node) {
  if (user_access('create platform git-pull task') && isset($node->git['git_allow_pull_task'])) {
    return $node->git['git_allow_pull_task'];
  }
  return TRUE;
}
/**
 * Implements hook_permission().
 */
function hosting_git_permission() {
  return array(
    'create git-pull task' => array(
      'title' => t('create git-pull task'),
      'description' => t('TODO Add a description for \'create git-pull task\''),
    ),
    'create git_clone task' => array(
      'title' => t('create git_clone task'),
      'description' => t('TODO Add a description for \'create git_clone task\''),
    ),
    'create git_checkout task' => array(
      'title' => t('create git_checkout task'),
      'description' => t('TODO Add a description for \'create git_checkout task\''),
    ),
    'create platform git-pull task' => array(
      'title' => t('create platform git-pull task'),
      'description' => t('TODO Add a description for \'create platform git-pull task\''),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function hosting_git_menu() {
  $items['admin/hosting/git'] = array(
    'title' => 'Git',
    'description' => 'Configure Git integration',
    'file' => 'hosting_git.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_git_settings_form'),
    'access arguments' => array('administer hosting settings'),
    'tab_parent' => 'admin/hosting',
    'type' => MENU_LOCAL_TASK,
  );
  $items[HOSTING_GIT_PULL_CALLBACK_URL] = array(
    'page callback' => 'hosting_git_pull_callback',
    'access callback' => TRUE,
    'file' => 'hosting_git_pull.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function hosting_git_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'platform_node_form') {
    $form['git'] = array(
      '#type' => 'fieldset',
      '#tree' => TRUE,
      '#title' => t('Deploy from Git'),
      '#collapsible' => TRUE,
      '#description' => t('You may deploy this platform from a Git repository. This functionality cannot be combined with a Makefile.'),
      '#weight' => -1,
    );

    $form['git']['repo_url'] = array(
      '#type' => 'textfield',
      '#title' => 'Repository URL',
      '#description' => t('The full URL that you would pass to <em>git clone</em>. Example:  git@github.com:username/project.git or https://github.com/username/project.git. Note that this repository must be accessible by the Aegir user.'),
    );

    $form['git']['repo_branch'] = array(
      '#type' => 'textfield',
      '#title' => 'Branch or tag name',
      '#description' => t('If a branch or tag name is not supplied, the platform will be deployed from <em>master</em>. This must match the Git branch or tag name exactly.'),
    );
    // repo_url and branch are currently not editable
    if (0 && !is_null($form['nid']['#value'])) {
      $form['git']['repo_url']['#disabled'] = TRUE;
      $form['git']['repo_branch']['#disabled'] = TRUE;
      $form['git']['repo_url']['#description'] = t('Only available on node creation');
      $form['git']['repo_branch']['#description'] = $form['git']['repo_url']['#description'];
    }

    $form['git']['git_allow_pull_task'] = array(
      '#type' => 'checkbox',
      '#title' => 'Allow git pull',
      '#description' => t('Allow the use of a git pull task to update the platform'),
      '#default_value' => $form['#node']->git['git_allow_pull_task'],
    );

    $form['#validate'][] = 'hosting_platform_git_node_form_validate';
  }
  if ($form_id == 'site_node_form') {
    // Get node
    $node = $form['#node'];

    // Get default value
    if (is_null($node->pull_method)) {
      $node->pull_method = HOSTING_GIT_PULL_DISABLED;
    }

    //All settings git pull in project page
    $form['git_settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('Git Settings'),
    );

    $form['git_settings']['pull_method'] = array(
      '#title' => 'Automatic Git Pull Method',
      '#type' => 'radios',
      '#description' => t('Choose the method of regularly calling "Pull Code". See !link to configure the queue. See !link2 to configure URL Callback.', array(
        '!link' => l(t('Hosting > Queues'), 'admin/hosting/queues'),
        '!link2' => l(t('Hosting > DevShop Pull Settings'), 'admin/hosting/hosting_git_pull'),
      )),
      '#default_value' => $node->pull_method,
      '#options' => array(
        HOSTING_GIT_PULL_DISABLED => t('Pull disabled.'),
        HOSTING_GIT_PULL_QUEUE => t('Pull on queue (every minute).'),
        HOSTING_GIT_PULL_CALLBACK => t('Pull on URL Callback (ie. GitHub Webhook)'),
      ),
    );
    module_load_include('inc', 'hosting_git_pull');
    $form['git_settings']['pull_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Pull Trigger URL'),
      '#value' => _hosting_git_pull_callback_url($node),
      '#description' => t('Configure your repo to hit this URL when it receives a commit.'),
      '#attributes' => array(
        'onclick' => 'this.select()',
      ),
    );

    // @TODO: is there a better way to save certain values? We lose data without these.
    $form['git_settings']['last_pull'] = array(
      '#type' => 'value',
      '#value' => $node->last_pull,
    );
    $form['git_settings']['last_pull_status'] = array(
      '#type' => 'value',
      '#value' => $node->last_pull_status,
    );
    $form['git_settings']['last_pull_ip'] = array(
      '#type' => 'value',
      '#value' => $node->last_pull_ip,
    );
  }
}

/**
 * Validation callback for platform node form.
 */
function hosting_platform_git_node_form_validate($form, &$form_state) {
  if (!empty($form_state['values']['git']['repo_url']) && !empty($form_state['values']['makefile'])) {
    form_set_error('makefile', t('Git deployment and Makefile deployment cannot be combined'));
  }
}

/**
 * Implements hook_nodeapi().
 */
function hosting_git_nodeapi_OLD(&$node, $op) {
  // TODO Remaining code in this function needs to be moved to the appropriate new hook function.
  if ($node->type == 'platform') {
    switch ($op) {
      case 'update':
        // TODO Please review the conversion of this statement to the D7 database API syntax.
        /* db_query('UPDATE {hosting_platform_git} SET git_allow_pull_task=%d WHERE nid = %d', $node->git['git_allow_pull_task'], $node->nid) */
        db_update('hosting_platform_git')
  ->fields(array(
          'git_allow_pull_task' => $node->git['git_allow_pull_task'],
        ))
  ->condition('nid', $node->nid)
  ->execute();
        break;
      case 'insert':
        $info = new stdClass();
        $info->nid = $node->nid;
        $info->git_repo_url = !empty($node->git['repo_url']) ? $node->git['repo_url'] : 'NOOP';
        $info->git_repo_branch = !empty($node->git['repo_branch']) ? $node->git['repo_branch'] : 'master';
        $info->git_repo_allow_pull = !empty($node->git['git_allow_pull_task']) ? $node->git['git_allow_pull_task'] : FALSE;
        if ($node->is_new) {
          drupal_write_record('hosting_platform_git', $info);
        }
        else {
          drupal_write_record('hosting_platform_git', $info, 'nid');
        }
        break;
      case 'load':
        if ($result = db_fetch_object(db_query('SELECT * FROM {hosting_platform_git} WHERE nid = :nid', array(':nid' => $node->nid)))) {
          $node->git = array();
          $node->git['repo_url'] = $result->git_repo_url;
          $node->git['repo_branch'] = $result->git_repo_branch;
          $node->git['git_allow_pull_task'] = $result->git_allow_pull_task;
        }
        break;
      case 'view':
        if (isset($node->git['repo_url']) && $node->git['repo_url'] != 'NOOP') {
          $node->content['info']['git_repo_url'] = array(
            '#type' => 'item',
            '#title' => t('Repository URL'),
            '#weight' => 100,
            '#value' => check_plain($node->git['repo_url']),
          );
          $node->content['info']['git_repo_branch'] = array(
            '#type' => 'item',
            '#title' => t('Repository branch/tag'),
            '#weight' => 100,
            '#value' => check_plain($node->git['repo_branch']),
          );
        }
        break;
    }
  }
}

/**
 * Implementation of hook_form()
 */
function hosting_task_git_pull_form($node) {

  $form['reset_hard'] = array(
    '#title' => t('Force: Reset --hard before pulling?'),
    '#description' => t("Uncommitted changes will be lost."),
    '#type' => 'checkbox',
    '#weight' => '-1',
    '#default_value' => TRUE,
  );

  return $form;
}
/**
 * Implementation of hook_form()
 */
function hosting_task_git_clone_form($node) {

  $site_path = _hosting_git_getsitepath($node);

  if ($site_path) {

    // The git repo
    $form['gitrepo'] = array(
      '#title' => t('Git repository'),
      '#description' => t("Enter the repository string you want to clone."),
      '#type' => 'textfield',
      '#required' => TRUE,
      '#weight' => '-1',
      '#default_value' => '',
    );

    // The location where the repo should be cloned
    // We currently support modules, libraries, themes and settings
    $options = _hosting_git_getgitlocations();

    $form['location'] = array(
      '#title' => t('Location'),
      '#type' => 'radios',
    );


    foreach ($options as $key => $option) {

      $form['location'][$key] = array(
        '#type' => 'radio',
        '#title' => $option,
        '#return_value' => $key,
        '#parents' => array('location'),
      );

      if (!_hosting_git_isdirempty($site_path . '/' . $key)) {
        $form['location'][$key]['#disabled'] = TRUE;
        $form['location'][$key]['#description'] = t('The target directory for %option is not empty. Git needs an empty directory for the clone operation', array('%option' => $option));
      }
    }
  }
  else {
    $form['error'] = array(
      '#type' => 'markup',
      '#value' => t('We were not able to determine the path on the file system where the site is published.'),
    );
    // TODO Check if this works
    $form['submit']['#disabled'] = TRUE;
  }

  $form['#node'] = $node;
  return $form;
}

/**
 * Implements hook_validate()
 */
function hosting_task_git_clone_form_validate($form, &$form_state) {
  // Pass the value from location to the parameters location
  $form_state['values']['parameters']['location'] = $form_state['values']['location'];
}

/**
 * Implementation of hook_form()
 */
function hosting_task_git_checkout_form($node) {
  // Get the path to the site
  $site_path = _hosting_git_getsitepath($node);

  // We can only perform a checkout when there's a path and there's a git repository
  if ($site_path) {
    // The git repo
    $form['tag'] = array(
      '#title' => t('The tag name'),
      '#description' => t("Enter the name of the tag. This should already exist in the local clone, so you might have to pull first."),
      '#type' => 'textfield',
      '#required' => TRUE,
      '#weight' => '-1',
      '#default_value' => '',
    );

    // Check for locations where we can perform a checkout
    $options = _hosting_git_getgitlocations();

    $form['location'] = array(
      '#title' => t('Location'),
      '#type' => 'radios',
    );

    foreach ($options as $key => $option) {

      $form['location'][$key] = array(
        '#type' => 'radio',
        '#title' => $option,
        '#return_value' => $key,
        '#parents' => array('location'),
      );

      if (!is_dir($site_path . '/' . $key . '/.git')) {
        $form['location'][$key]['#disabled'] = TRUE;
        $form['location'][$key]['#description'] = t('The target directory for %option has no .git directory. The git checkout command needs a git repo present.', array('%option' => $option));
      }
    }
  }
  else {
    $form['error'] = array(
      '#type' => 'markup',
      '#value' => t('We were not able to determine the path on the file system where the site is published.'),
    );
    // TODO Check if this works
    $form['submit']['#disabled'] = TRUE;
  }

  $form['#node'] = $node;
  return $form;
}

/**
 * Implementation of hook_validate()
 */
function hosting_task_git_checkout_form_validate($form, &$form_state) {
  // Pass the value from location to the parameters location
  $form_state['values']['parameters']['location'] = $form_state['values']['location'];
}

/**
 * Implements hook_hosting_queues().
 */
function hosting_git_pull_hosting_queues() {
  $items['pull'] = array(
    'type' => 'batch',
    'name' => t('Pull queue'),
    'description' => t('Run git pull on projects configured to do so.'),
    'total_items' => _hosting_git_pullqueue_get_platforms(10),
    'frequency' => strtotime("1 minute", 0),
    'singular' => t('project'),
    'plural' => t('projects'),
  );
  return $items;
}
/**
 * Implements hosting_QUEUE_TYPE_queue().
 */
function hosting_pull_queue($count) {

  $result = db_query("SELECT d.*  FROM {hosting_hosting_git_project_object} dpo LEFT JOIN {hosting_hosting_git_pull_projects}  d ON dpo.project_nid=d.project_nid WHERE d.pull_method = :d.pull_method AND dpo.object_type = :dpo.object_type ORDER BY d.last_pull ASC, dpo.object_nid ASC", array(':d.pull_method' => array(HOSTING_GIT_PULL_QUEUE), ':dpo.object_type' => 'platform'));

  while ($project = db_fetch_object($result)) {
    $project_node = node_load($project->project_nid);

    // Create the hosting task
    // @TODO: We maybe don't need to pass args here? its saved in the context
    // Check for environments set to pull
    $environments_to_pull = array();
    foreach ($project_node->settings as $env => $settings) {
      if ($settings['pull_enabled']) {
        $environments_to_pull[] = $env;
      }
    }
    $args = array();
    $args['environments'] = implode(' ', $environments_to_pull);
    hosting_add_task($project_node->nid, 'devshop-pull', $args);

    module_invoke_all('hosting_git_pull', $project_node);
  }
}

/**
 * Get a number of platforms that have their pull queue enabled.
 *
 * @param $limit
 *   Limit to a maximum of this number of platforms.
 * @return
 *   An array of site nodes that have a pull queue enabled.
 *
 * @TODO Convert to check pull queue sites.
 */
function _hosting_git_pullqueue_get_platforms($limit = 5) {
  $result = db_query("SELECT COUNT(dpo.object_nid) FROM {hosting_hosting_git_project_object} dpo LEFT JOIN {hosting_hosting_git_pull_projects}  d ON dpo.project_nid=d.project_nid WHERE d.pull_method = :d.pull_method  AND dpo.object_type = :dpo.object_type ORDER BY d.last_pull ASC, dpo.object_nid ASC", array(':d.pull_method' => array(HOSTING_GIT_PULL_QUEUE), ':dpo.object_type' => 'platform'));
  return $result->fetchField();
}


/* Private functions */

function _hosting_git_isdirempty($dir) {
  // Check to see if the target dir is empty
  if ($handle = @opendir($dir)) {
    // open directory
    while (($file = readdir($handle)) !== FALSE) {
      if ($file != "." && $file != "..") {
        closedir($handle); // Close directory
        return FALSE;
      }
    }
    closedir($handle); // Close directory
  }
  return TRUE;
}

function _hosting_git_getsitepath($node) {
  // Select the platform publish_path for $node->platform
  $platform_publishpath = db_query("SELECT publish_path FROM {hosting_platform} WHERE nid = :nid", array(':nid' => $node->platform))->fetchField();

  if ($platform_publishpath) {
    return $platform_publishpath . '/sites/' . $node->title;
  }
  else {
    return FALSE;
  }
}

function _hosting_git_getgitlocations() {
  // TODO Should we make this configurable?
  return array(
    '.' => t('Site specific folder root'),
    'modules' => t('Modules'),
    'themes' => t('Themes'),
    'libraries' => t('Libraries'),
  );
}
